### ISSUE TITLE
AWS lambdaのStage環境を用意する

### ISSUE THREAD

**Issue by wanshot** [beproud/bp-cron#26]
## 前提

* bp-cronは現状ローカル環境と本番環境(aws lambda)で処理を実行する事ができる
* 本番環境へのデプロイはCircleCIから行っている

## 目的

* いちいちAWSにログインしてlambdaのコンソールでぽちぽちしないでもいいように今のローカル環境開発を残しつつ、lambda特有の動作検証、確認の為にStage環境を用意したい
* 現状ローカル環境からそのまま本番環境へのデプロイを行える状態を防ぎたい

**Comment by wanshot** [comment]
gitのtagと連動させると管理が楽になるかも

https://beproud.slack.com/archives/G0291Q891/p1572393092019300

**Comment by wanshot** [comment]
## 要件

* PR時はunittestのみを実行
* masterにマージされたらunittest実行後stage環境へデプロイ
* tagが発行されたらunittest実行後prod環境へデプロイ
* stage環境のタスクはローカルからのタスク実行コマンドで動かす(定期実行しない)

## 案

CircleCiの方
```
# deploy-prod と deploy-stage のデプロイコマンド実行時にそれぞれの環境を指定する
# https://serverless.com/framework/docs/providers/aws/guide/variables/
test-and-deploy:
  jobs:
  - test-job
  - deploy-stage:
      filters:
        branches:
          only:
          - master
      requires:
      - test-job
  - deploy-prod:
      branches:
        ignore: /.*/
      tags:
         only: /^v[0-9](\.[0-9]){2}$/
      requires:
      - test-job
```

stageの時に定期実行させない方法は以下でいけそう

* https://github.com/serverless/serverless/issues/3323#issuecomment-500545350
